package org.itson.bda.BancoMB.bancoMB;

import javax.swing.table.DefaultTableModel;
import org.itson.bda.proyectobda_247164_246943.daos.IClientesDAO;
import org.itson.bdavanzadas.clubnauticopersistencia.dtos.ClienteNuevoDTO;

/**
 * La clase publica `ClientesForm` representa la interfaz gráfica para realizar operaciones
 * relacionadas con retiros de efectivo en la aplicacción del banco MB.
 */
public class ClientesForm extends javax.swing.JFrame {

    public int monto;
    public String concepto;
    private Acciones opcion;
    private final IClientesDAO clientesDAO;
    DefaultTableModel modelo;
     /**
     * Constructor de la clase `ClientesForm`.
     * @param clientesDAO Interfaz para acceder a la capa de acceso de datos relacionada con clientes.
     */
    public ClientesForm(IClientesDAO clientesDAO) {
        initComponents();
        this.clientesDAO = clientesDAO;
        // Configuración de botones de las acciones aceptar y cancelar.
        if (opcion == Acciones.CANCELAR) {
            btnCancelar.setText("Cancelar");

        } else if (opcion == Acciones.ACEPTAR) {
            btnAceptar.setText("Aceptar");
            btnAceptar.setText(txtConcepto.getText());
            btnAceptar.setText(txtOtraCifra.getText());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn200 = new javax.swing.JButton();
        btn300 = new javax.swing.JButton();
        btn400 = new javax.swing.JButton();
        btn500 = new javax.swing.JButton();
        btn1000 = new javax.swing.JButton();
        LblImporte = new javax.swing.JLabel();
        txtConcepto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtOtraCifra = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btn100 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retiro sin cuenta");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
   
        btn200.setText("$200");
        btn200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn200ActionPerformed(evt);
            }
        });
        jPanel1.add(btn200, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));
        btn300.setText("$300");
        jPanel1.add(btn300, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));
        btn400.setText("$400");
        btn400.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn400ActionPerformed(evt);
            }
        });
        jPanel1.add(btn400, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        btn500.setText("$500");
        btn500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500ActionPerformed(evt);
            }
        });
        jPanel1.add(btn500, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));
        
        btn1000.setText("$1000");
        btn1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        LblImporte.setText("Importe");
        jPanel1.add(LblImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        txtConcepto.setText("Concepto (opcional)");
        txtConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConceptoActionPerformed(evt);
            }
        });

        jPanel1.add(txtConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 260, -1));

        jLabel1.setText("Solo múltiplos de 100");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        txtOtraCifra.setText("Otra Cifra");
        txtOtraCifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtraCifraActionPerformed(evt);
            }
        });
        jPanel1.add(txtOtraCifra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 260, -1));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        btn100.setText("$100");
        btn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ActionPerformed(evt);
            }
        });
        jPanel1.add(btn100, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /** 
    * @param evt Boton de retiro sin cliente que selecciona la cantidad de $200 pesos.
    */
    private void btn200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn200ActionPerformed
        System.out.print(200);
    }//GEN-LAST:event_btn200ActionPerformed
    /**
    * @param evt Boton de retiro sin cliente que selecciona la cantidad de $400 pesos.
    */
    private void btn400ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn400ActionPerformed
        System.out.print(400);    }//GEN-LAST:event_btn400ActionPerformed
    /**
     * @param evt Boton de retiro sin cliente que selecciona la cantidad de $500 pesos.
     */
    private void btn500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500ActionPerformed
        System.out.print(500);    }//GEN-LAST:event_btn500ActionPerformed
    /**
    * @param evt Boton de retiro sin cliente que selecciona la cantidad de $100 pesos.
    */
    private void btn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ActionPerformed
        System.out.print(100);    }//GEN-LAST:event_btn100ActionPerformed
    /**
    * @param evt txtConcepto, texto referente al campo de texto de concepto del retiro sin cuenta.
    */
    private void txtConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConceptoActionPerformed
        txtConcepto.getText();
    }//GEN-LAST:event_txtConceptoActionPerformed
    /**
    * @param evt textOtraCifra, texto referente al campo de texto de concepto del retiro sin cuenta.
    */
    private void txtOtraCifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtraCifraActionPerformed
        txtOtraCifra.getText();
    }//GEN-LAST:event_txtOtraCifraActionPerformed
    /**
    * @param evt Boton de retiro sin cliente que selecciona la cantidad de $1000 pesos.
    */
    private void btn1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000ActionPerformed
        System.out.print(1000);    }//GEN-LAST:event_btn1000ActionPerformed
    /**
    * @param evt Método de acción para el botón "Aceptar".
    */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String concepto = txtConcepto.getText();
        String otraCifra = txtOtraCifra.getText();
        btnAceptar.setText(concepto + " - " + otraCifra);
        clientesDAO.agregar(concepto, otraCifra);


    }//GEN-LAST:event_btnAceptarActionPerformed
    /**
    * @param evt Método de acción para el botón "Cancelar".
    */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblImporte;
    private javax.swing.JButton btn100;
    private javax.swing.JButton btn1000;
    private javax.swing.JButton btn200;
    private javax.swing.JButton btn300;
    private javax.swing.JButton btn400;
    private javax.swing.JButton btn500;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextField txtOtraCifra;
    // End of variables declaration//GEN-END:variables
}
