/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyectobda_247164_246943;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class NewJDialogRetiroSinCuenta extends javax.swing.JDialog {
    
//    FondoPanel fondo = FondoPanel();

    /**
     * Creates new form NewJDialogRetiroSinCuenta
     * @param parent
     * @param modal
     */
    public NewJDialogRetiroSinCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
//        this.setContentPane(fondo);
        initComponents();
        
        
        


    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton$201 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();
        jLabelImporte = new javax.swing.JLabel();
        jTextFieldOtro = new javax.swing.JTextField();
        jButtonContinuar = new javax.swing.JButton();
        jLabelRetiroSinCuentaTitulo = new javax.swing.JLabel();
        jLabelOtro = new javax.swing.JLabel();
        jLabelEspecificacion = new javax.swing.JLabel();
        jButton$100 = new javax.swing.JButton();
        jButton$200 = new javax.swing.JButton();
        jButton$300 = new javax.swing.JButton();
        jButton$400 = new javax.swing.JButton();
        jButton$500 = new javax.swing.JButton();
        jButton$1000 = new javax.swing.JButton();
        jTextFieldConcepto = new javax.swing.JTextField();

        jButton$201.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton$201.setForeground(new java.awt.Color(0, 0, 51));
        jButton$201.setText("$200");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelFondo.setText(".");

        jLabelImporte.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelImporte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImporte.setText("IMPORTE");

        jTextFieldOtro.setBackground(new java.awt.Color(236, 235, 235));
        jTextFieldOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOtroActionPerformed(evt);
            }
        });

        jButtonContinuar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonContinuar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButtonContinuar.setText("Continuar");
        jButtonContinuar.setActionCommand("Continuar");
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });

        jLabelRetiroSinCuentaTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelRetiroSinCuentaTitulo.setForeground(new java.awt.Color(0, 0, 153));
        jLabelRetiroSinCuentaTitulo.setText("Retiro sin cuenta");

        jLabelOtro.setText("Otro");

        jLabelEspecificacion.setText("Solo multiplos de 100");

        jButton$100.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton$100.setForeground(new java.awt.Color(0, 0, 51));
        jButton$100.setText("$100");

        jButton$200.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton$200.setForeground(new java.awt.Color(0, 0, 51));
        jButton$200.setText("$200");

        jButton$300.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton$300.setForeground(new java.awt.Color(0, 0, 51));
        jButton$300.setText("$300");

        jButton$400.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton$400.setForeground(new java.awt.Color(0, 0, 51));
        jButton$400.setText("$400");

        jButton$500.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton$500.setForeground(new java.awt.Color(0, 0, 51));
        jButton$500.setText("$500");

        jButton$1000.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton$1000.setForeground(new java.awt.Color(0, 0, 51));
        jButton$1000.setText("$1000");

        jTextFieldConcepto.setBackground(new java.awt.Color(236, 235, 235));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton$100)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton$500)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton$1000))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelImporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton$200, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton$300)
                                    .addComponent(jLabelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton$400, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabelRetiroSinCuentaTitulo)))
                        .addGap(148, 148, 148))))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabelOtro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonContinuar)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelEspecificacion)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldOtro, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelRetiroSinCuentaTitulo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelImporte)
                            .addComponent(jLabelFondo))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton$100)
                            .addComponent(jButton$200)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton$300)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton$400)
                            .addComponent(jButton$500)
                            .addComponent(jButton$1000))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jTextFieldOtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabelOtro)
                .addGap(4, 4, 4)
                .addComponent(jLabelEspecificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonContinuar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOtroActionPerformed

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewJDialogRetiroSinCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewJDialogRetiroSinCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewJDialogRetiroSinCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewJDialogRetiroSinCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                NewJDialogRetiroSinCuenta dialog = new NewJDialogRetiroSinCuenta(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton$100;
    private javax.swing.JButton jButton$1000;
    private javax.swing.JButton jButton$200;
    private javax.swing.JButton jButton$201;
    private javax.swing.JButton jButton$300;
    private javax.swing.JButton jButton$400;
    private javax.swing.JButton jButton$500;
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JLabel jLabelEspecificacion;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelImporte;
    private javax.swing.JLabel jLabelOtro;
    private javax.swing.JLabel jLabelRetiroSinCuentaTitulo;
    private javax.swing.JTextField jTextFieldConcepto;
    private javax.swing.JTextField jTextFieldOtro;
    // End of variables declaration//GEN-END:variables

//class FondoPanel extends JPanel
//{
//    private Image Imagen;
//    
//    @Override
//    public void paint (Graphics g)
//    {
//        Imagen = new ImageIcon (getClass().getResource ("/com.mycompany.IMAGENES/AZULFONDO")).getImage();
//        
//        g.drawImage(Imagen,0, 0, getWidth(), getHeight(), this);
//        
//        setOpaque(false);
//        
//        super.paint(g);
//    }
//    
//}
}

